---
title: Gae Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    author_profile: true
- scope:
    path: ''
    type: posts
  values:
    layout: single
    toc: true
    toc_sticky: true
    share: true
    related: true
    show_date: true
    read_time: true
    comments: true
subtitle: Notes, Word Salad, etc.
brief-intro: Software Engineer@Amazon
baseurl: ''
url: https://www.gaeblog.com
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
repository: SeraphRoy/SeraphRoy.github.io
plugins:
- jekyll-paginate
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-archives
algolia:
  application_id: VQQEF0782J
  index_name: VQQEF0782J
  search_only_api_key: b66031155929f70634dffecb4a9d7eba
  powered_by: false
search: true
search_provider: algolia
comments:
  provider: disqus
  disqus:
    shortname: https-seraphroy-github-io-1
social:
  type: Person
  name: Yanxi Chen
  links:
  - https://www.linkedin.com/in/yanxichen
  - https://github.com/SeraphRoy
analytics:
  provider: google-gtag
  google:
    tracking_id: G-40LC9SH4E1
    anonymize_ip: false
author:
  name: Yanxi Chen
  avatar: "/assets/avatar1.jpeg"
  bio: Software Engineer@Amazon
  location: California, USA
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/SeraphRoy
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/yanxichen/
paginate: 6
category_archive:
  type: jekyll-archives
  path: "/categories/"
tag_archive:
  type: jekyll-archives
  path: "/tags/"
jekyll-archives:
  enabled:
  - categories
  - tags
  - year
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
    year: archive-taxonomy
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"
words_per_minute: 200
include:
- _pages
- _includes
atom_feed:
  hide: true
head_scripts:
- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
- "/assets/js/mathjax-config.js"
- https://identity.netlify.com/v1/netlify-identity-widget.js
- "/assets/js/netlify-identity.js"
after_footer_scripts:
- https://unpkg.com/vanilla-back-to-top@7.2.1/dist/vanilla-back-to-top.min.js
- "/assets/js/back-to-top.js"
