# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GaeBlogX
brief-intro: "Arista Networks, CloudVision® Portal"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seraphroy.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
# twitter_username: gaohaoyang126
facebook_username: SeraphRoy
github_username: SeraphRoy
email: royxagain@gmail.com
# weibo_username: 3115521wh
# zhihu_username: gaohaoyang
linkedIn_username: yanxichen
# dribbble_username:

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: https-seraphroy-github-io-1

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id:
google_analytics_id: UA-100686813-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "<!--more-->"

# paginate
plugins:
    - jekyll-paginate
    - jekyll-seo-tag
paginate: 6

algolia:
   application_id: 'VQQEF0782J'
   index_name:     'VQQEF0782J'
   search_only_api_key: 'b66031155929f70634dffecb4a9d7eba'
